### ISSUE TITLE
Float window not closing

### ISSUE THREAD

**Issue by ryan0270** [matsui54/ddc-nvim-lsp-doc#11]
When I open parenthesis for a function the float pops up as expected but then it never goes away. I expected the float to go away when I closed parenthesis for the function or escape out of edit mode.

![image](https://user-images.githubusercontent.com/3256707/147852463-bce7f2d2-21c7-4836-82b9-2b14591c4dc3.png)

```c++
float foo(int a, double b)
{
  return 1.f;
}

int main(int, char**)
{
  if(foo(1,2) 
  {
    return 1;
  }
  return 0;
}
```

* latest version of all plugins (called `dein#update()` before testing)
* `checkhealth` reports no problems (except missing python 2)
* Arch Linux (freshly updated)
* nvim info
```
NVIM v0.6.1
LuaJIT 2.0.5
```
* init.vim
```vim
" .#vimrc
if &compatible
  set nocompatible
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
call dein#begin('~/.cache/dein')

call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
call dein#add('Shougo/ddc-nvim-lsp')
call dein#add('Shougo/ddc.vim')
call dein#add('matsui54/ddc-nvim-lsp-doc')
call dein#add('neovim/nvim-lspconfig')
call dein#add('vim-denops/denops.vim')
call dein#end()
call dein#save_state()

call ddc#enable()
call ddc_nvim_lsp_doc#enable()
lua require('lspconfig').clangd.setup{cmd={'clangd'}}
```

**Comment by matsui54** [comment]
I fixed. Thank you for reporting!
But, from today, this plugin is no longer maintained. Please use [denops-popup-preview.vim](https://github.com/matsui54/denops-popup-preview.vim) and [denops-signature_help](https://github.com/matsui54/denops-signature_help) instead.

You can use them like this.
```vim
call popup_preview#enable()
call signature_help#enable()
```
