### ISSUE TITLE
`nvim_win_close()` crash

### ISSUE THREAD

**Issue by Shougo** [matsui54/ddc-nvim-lsp-doc#3]
![スクリーンショット_2021-09-05_17-15-28](https://user-images.githubusercontent.com/41495/132120291-f43c111e-1777-46e3-b164-8f518fa8d7af.png)

**Comment by Shougo** [comment]
It should check `winnr('$')` value.
And it should use `winid` instead of current widow.
Current window may be changed.

**Comment by matsui54** [comment]
Thanks for reporting.
The invalid id `0` in the error message is not window number but error value of `nvim_open_win()`.
So this is a problem of opening windows.

For workaround, I will add error check of `nvim_open_win()`.

**Comment by Shougo** [comment]
Oh, OK.

**Comment by matsui54** [comment]
Can you update and check it?

**Comment by Shougo** [comment]
Thanks.  I will update it.

**Comment by Shougo** [comment]
It seems fixed.

**Comment by matsui54** [comment]
That's good! Thanks for checking.
