### ISSUE TITLE
I cannot see the input text

### ISSUE THREAD

**Issue by Shougo** [matsui54/ddc-nvim-lsp-doc#4]
Please see the screenshot.

I think the plugin should check border line.

![スクリーンショット_2021-09-11_15-09-48](https://user-images.githubusercontent.com/41495/132938314-b2f02702-3697-4212-be04-2ce609c5b72c.png)

**Comment by matsui54** [comment]
OK. I will add new highlight which links to `NormalFloat`.

**Comment by matsui54** [comment]
I added `DdcNvimLspDocBorder` highlight which is linked to `NormalFloat`.
You can also customize highlight with this value.
Can you update it?

**Comment by Shougo** [comment]
Thanks.  It is better.  But I cannot read the input text...
I think the position should be moved to bottom.

![スクリーンショット_2021-09-12_22-14-42](https://user-images.githubusercontent.com/41495/132988975-bb9c82d7-b249-4f9b-a383-14668eabcd63.png)

**Comment by matsui54** [comment]
Oh, I get it. I didn't take tabline into consideration.

**Comment by matsui54** [comment]
Fixed. Please update it.

**Comment by Shougo** [comment]
Thanks.  It is perfect!
