### ISSUE TITLE
Support denops restart

### ISSUE THREAD

**Issue by Shougo** [matsui54/ddc-nvim-lsp-doc#6]
If denops.vim crashed, ddc-nvim-lsp-doc does not work like this.

![スクリーンショット_2021-09-18_14-51-40](https://user-images.githubusercontent.com/41495/133877738-22e862c4-17de-4f49-a77e-f1a80f2924c3.png)

I think the restart should be supported.

**Comment by Shougo** [comment]
I think `ddc#enable()` implementation is better instead of `g:ddc_nvim_lsp_doc#_initialized` check.

**Comment by matsui54** [comment]
Thanks! I will see ddc implementation later.

**Comment by matsui54** [comment]
Implemented. I wraped `denops#notify()` with a function which checks denops status.
