### ISSUE TITLE
[BUG] about ddc_nvim_lsp_doc#enable_signaturehelp

### ISSUE THREAD

**Issue by phgz** [matsui54/ddc-nvim-lsp-doc#9]
Hi,

I tried setting this global variable to `0`:
```vim
let g:ddc_nvim_lsp_doc#enable_signaturehelp = 0
```
I also tried setting it directly here:

```vim
let g:ddc_nvim_lsp_doc_config = {
        \ 'documentation': {
        \   'enable': v:true,
        \ },
        \ 'signature': {
        \   'enable': v:false,
        \ },
        \ }

```

, however it still shows the signature help. I checked for the variable in the code and is does not seem to be referenced anywhere. It is implemented?

Thanks!

**Comment by phgz** [comment]
Otherwise, features that could be nice are the possibility to have different highlights for the signatureHelp and the PUM's LSP documentation and also have the possibility to hide/toggle the signatureHelp with a command and update the actual parameter on `,`.

**Comment by matsui54** [comment]
Thanks for reporting! I fixed and removed variable `g:ddc_nvim_lsp_doc#enable_signaturehelp` as this was duplicated option.
